import { ThemeContextProvider } from '@/context/ThemeContext';
import GlobalStyle from '@/styles/GlobalStyle';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <ThemeContextProvider>
          <GlobalStyle />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
